export enum ActionType {
  SET_DATA = "SET_DATA",
  DELETE_ITEM = "DELETE_ITEM",
  HANDLE_FORM_INPUT = "HANDLE_FORM_INPUT",
  SELECT_ITEM = "SELECT_ITEM",

  EDIT_ITEM = "EDIT_ITEM",
  ADD_ITEM = "ADD_ITEM",
  TOGGLE_MODAL = "TOGGLE_MODAL",
  SELECTED_LINK_TYPE = "SELECTED_LINK_TYPE",
}
