export enum ActionType {
  SET_DATA = "SET_DATA",
  DELETE_STARTED = "DELETE_STARTED",
  DELETE_ITEM = "DELETE_ITEM",
  HANDLE_FORM_INPUT = "HANDLE_FORM_INPUT",
  FORM_SUBMITTED = "FORM_SUBMITTED",
  SELECT_ITEM = "SELECT_ITEM",
  UPDATE_DATA_END = "UPDATE_DATA_END",

  EDIT_ITEM = "EDIT_ITEM",
  ADD_ITEM = "ADD_ITEM",
  TOGGLE_MODAL = "TOGGLE_MODAL",
  SELECTED_LINK_TYPE = "SELECTED_LINK_TYPE",

  SET_THEME_DATA = "SET_THEME_DATA",
  TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR",
  CHANGE_THEME_COLOR = "CHANGE_THEME_COLOR",
  CHANGE_THEME_LAYOUT = "CHANGE_THEME_LAYOUT",
}
